# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('product', models.CharField(blank=True, max_length=128)),
                ('news', models.ManyToManyField(blank=True, to='news.News')),
            ],
        ),
    ]
