# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
