# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('products', '0002_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='news',
            field=models.ManyToManyField(blank=True, to='news.News'),
        ),
    ]
