# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='changes',
        ),
        migrations.AddField(
            model_name='news',
            name='changes',
            field=models.ManyToManyField(blank=True, to='news.VersionChange'),
        ),
    ]
