- hosts: all
  tasks:
    - include: 'tasks/install_nginx.yml'
    - include: 'tasks/install_docker.yml'
    - include: 'tasks/configure_nginx.yml'
    - include: 'tasks/first_deployment/selinux_and_docker_overlay.yml'
