- name: kill all previously existed containers
  docker:
    name: aeupdates
    image: aeupdates
    state: killed

- name: Copy docker config file
  copy: src=django_docker/Dockerfile dest=/aeupdates/Dockerfile  owner=root group=root mode=0644

- name: Copy docker runer
  copy: src=django_docker/docker_run.sh dest=/aeupdates/docker_run.sh

- name: Step for invalidating docker cache
  shell: echo `date` > /aeupdates/build_time

- name: Rebuild Container
  command: docker build -t aeupdates /aeupdates

#- copy: src=django_docker/build_date dest=/aeupdates/build_date
- name: Start container
  command: docker run -d -p 8080:8080 -p 8084:8084 -t aeupdates
